Allwmake: fixed how Metis is being built.

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -374,8 +374,30 @@ then
               touch mingw.patch.complete
         fi
 
-        [ -d build ] && rm -rf build
+        if [ -d build ]
+        then
+            mv build build.$$
+            rm -rf build.$$ &
+        fi
+
         [ ! -d build ] && mkdir build
+
+        if [ "$WM_PRECISION_OPTION" = "DP" ]
+        then
+            FLOAT_PRECISION=64
+        elif [ "$WM_PRECISION_OPTION" = "SP" ]
+        then
+            FLOAT_PRECISION=32
+        else
+            echo " Metis pre-configure error:"
+            echo "    WM_PRECISION_OPTION is neither DP nor SP"
+            exit 1
+        fi
+
+        # Change user settings automatically
+        sed -i -e 's=\(#define IDXTYPEWIDTH\).*=\1 '$WM_LABEL_SIZE'=' \
+               -e 's=\(#define REALTYPEWIDTH\).*=\1 '$FLOAT_PRECISION'=' \
+            include/metis.h
 
         cd build
         cmake \
