Allwmake: Recovered our hacks for building things on Windows.

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -79,8 +79,24 @@ echo
 
 #------------------------------------------------------------------------------
 
+# Build 3rd-party software that is only relevant to MinGW builds
+if isMinGW; then
+
+  ./AllwmakeMinGWStackTrace
+
+fi
+
+
 echo ========================================
 echo Build MPI libraries if required
+echo
+
+if isMinGW; then # MPI MinGW
+
+    ./AllwmakeMinGWMPI
+
+else # MPI linux
+
 case "$WM_MPLIB" in
 OPENMPI)
     if [ -r $MPI_ARCH_PATH/lib${WM_COMPILER_LIB_ARCH}/libmpi.so ]
@@ -221,6 +237,14 @@ checkSystemLibrary()
 #------------------------------------------------------------------------------
 
 # Scotch
+
+#either build the MinGW version or the standard version
+if isMinGW; then
+
+  ./AllwmakeMinGWScotch
+
+else
+
 
 # Scotch Makefile. Currently this is GCC specific.
 scotchMakefile=../../etc/wmakeFiles/scotch/Makefile.inc.i686_pc_linux2.shlib-OpenFOAM
@@ -383,6 +407,8 @@ then
 fi
 echo
 
+fi #end if isMinGW
+
 #------------------------------------------------------------------------------
 
 # METIS
@@ -398,6 +424,73 @@ system)
         "$METIS_LIB_DIR" "$METIS_INCLUDE_DIR"
     ;;
 OpenFOAM | ThirdParty)
+  if isMinGW; then
+  (
+
+    if [ -f $METIS_ARCH_PATH/include/metis.h \
+      -a -r $FOAM_EXT_LIBBIN/libmetis.dll ]
+    then
+        echo "    metis header in $METIS_ARCH_PATH/include"
+        echo "    metis libs   in $FOAM_EXT_LIBBIN"
+        echo
+    else
+        set -x
+        cd $METIS_VERSION  || exit 1
+        
+        if [ ! -e "mingw.patch.complete" ]; then
+            patch -p1 < $WM_THIRD_PARTY_DIR/etc/patches/patch_metis_5.1.0 && \
+              touch mingw.patch.complete
+        fi
+
+        if [ -d build ]
+        then
+            mv build build.$$
+            rm -rf build.$$ &
+        fi
+
+        [ ! -d build ] && mkdir build
+
+        if [ "$WM_PRECISION_OPTION" = "DP" ]
+        then
+            FLOAT_PRECISION=64
+        elif [ "$WM_PRECISION_OPTION" = "SP" ]
+        then
+            FLOAT_PRECISION=32
+        else
+            echo " Metis pre-configure error:"
+            echo "    WM_PRECISION_OPTION is neither DP nor SP"
+            exit 1
+        fi
+
+        # Change user settings automatically
+        sed -i -e 's=\(#define IDXTYPEWIDTH\).*=\1 '$WM_LABEL_SIZE'=' \
+               -e 's=\(#define REALTYPEWIDTH\).*=\1 '$FLOAT_PRECISION'=' \
+            include/metis.h
+
+        cd build
+        cmake \
+            -G "MSYS Makefiles" \
+            -DCMAKE_INSTALL_PREFIX=$METIS_ARCH_PATH \
+            -DCMAKE_BUILD_TYPE=Release \
+            -DSHARED=1 \
+            -DCMAKE_C_COMPILER=${WM_CC} \
+            -DGKLIB_PATH="../GKlib" \
+            -DCMAKE_C_FLAGS="$CFLAGS -DWIN${WM_ARCH_OPTION}" \
+            -DCMAKE_CXX_FLAGS="$CXXFLAGS -DWIN${WM_ARCH_OPTION}" \
+            $WM_THIRD_PARTY_DIR/$METIS_VERSION
+
+        make all install
+        cp $METIS_ARCH_PATH/lib/libmetis.dll* $FOAM_EXT_LIBBIN
+        cp $FOAM_EXT_LIBBIN/libmetis.dll.a $FOAM_EXT_LIBBIN/libmetis.a
+
+        #clean up afterwards
+        [ -d build ] && rm -rf build
+
+        set +x
+    fi
+  )
+  else
+
     . $($WM_PROJECT_DIR/bin/foamEtcFile config.sh/metis)
     if [ -f $METIS_ARCH_PATH/include/metis.h \
       -a -r $FOAM_EXT_LIBBIN/libmetis.so ]
@@ -427,7 +520,9 @@ OpenFOAM | ThirdParty)
             echo "(metis-$METIS_VERSION) were not found"
             exit 1
         fi
+
     fi
+  fi
     ;;
 esac
 echo
