Allwmake: Added support for building Zoltan with blueCFD-Core.

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -665,6 +665,49 @@ OpenFOAM | ThirdParty)
         fi
     fi
     ;;
+
+MSYS2)
+    echo "Zoltan is not provided with MSYS2 (up to mid July 2024)."
+    exit 1
+    ;;
+
+blueCFDCore)
+    . $($WM_PROJECT_DIR/bin/foamEtcFile config.sh/zoltan)
+    if [ -f $ZOLTAN_ARCH_PATH/include/zoltan.h \
+      -a -r $FOAM_EXT_LIBBIN/$FOAM_MPI/libzoltan.a ]
+    then
+        echo "ThirdParty installation of Zoltan decomposition found"
+        echo "    Zoltan header in $ZOLTAN_ARCH_PATH/include"
+        echo "    Zoltan libs   in $FOAM_EXT_LIBBIN/$FOAM_MPI"
+    else
+        echo "Building a ThirdParty installation of Zoltan decomposition"
+        if [ -d "Zoltan-$ZOLTAN_VERSION" ]
+        then
+        (
+            set -x
+            cd Zoltan-$ZOLTAN_VERSION  || exit 1
+            mkdir -p build
+            cd build
+            ../configure \
+                --prefix=$ZOLTAN_ARCH_PATH \
+                --libdir=$FOAM_EXT_LIBBIN/$FOAM_MPI \
+                --with-mpi=$MPI_ARCH_PATH \
+                --with-mpi-compilers=no \
+                --with-mpi-libdir=$MPI_ARCH_PATH/lib${WM_COMPILER_LIB_ARCH} \
+                --disable-zoltan-cppdriver \
+                --with-ccflags="$CFLAGS -DWIN${WM_ARCH_OPTION}" \
+                --with-cxxflags="$CXXFLAGS -DWIN${WM_ARCH_OPTION}"
+            make everything
+            make install
+        )
+        else
+            echo -n "    Error: ThirdPaty sources for Zoltan "
+            echo "(Zoltan-$ZOLTAN_VERSION) were not found"
+            exit 1
+        fi
+    fi
+    ;;
+
 esac
 echo
 
