Added and adapted files that are modified, based on the ones from blueCFD-Core 2.3-2

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -6,8 +6,12 @@
 #   \\  /    A nd           | Copyright (C) 2011-2014 OpenFOAM Foundation
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
+# 2014-02-20 blueCAPE Lda: Modifications for blueCFD-Core 2.3
+# 2016-03-14 blueCAPE Lda: Modifications for blueCFD-Core 2.3-2
+# 2016-07-22 blueCAPE Lda: Modifications for blueCFD-Core 2016-1
+#------------------------------------------------------------------------------
 # License
-#     This file is part of OpenFOAM.
+#     This file is a derivative work of OpenFOAM.
 #
 #     OpenFOAM is free software: you can redistribute it and/or modify it
 #     under the terms of the GNU General Public License as published by
@@ -21,6 +25,20 @@
 #
 #     You should have received a copy of the GNU General Public License
 #     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
+#
+# Modifications
+#     This file has been modified by blueCAPE's unofficial mingw patches for
+#     OpenFOAM.
+#     For more information about these patches, visit:
+#         http://bluecfd.com/Core
+#
+#     Modifications made:
+#        - Derived from the patches for blueCFD 2.1 and 2.2.
+#        - Added capabilities for building the stubs for: 
+#             Open-MPI, MPICH and MSMPI
+#        - Added capability for building Scotch for MinGW.
+#        - Added capability for building Metis for MinGW.
+#        - Added patches for TecIO and added back this build option.
 #
 # Script
 #     Allwmake
@@ -43,6 +61,7 @@ wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
     exit 1
 }
 . etc/tools/ThirdPartyFunctions
+. etc/tools/makeExtraThirdPartyFunctions
 #------------------------------------------------------------------------------
 
 # export WM settings in a form that GNU configure recognizes
@@ -62,6 +81,13 @@ echo
 echo ========================================
 echo Build MPI libraries if required
 echo
+
+if isMinGW; then # MPI MinGW
+
+    ./AllwmakeMinGWMPI
+
+else # MPI linux
+
 case "$WM_MPLIB" in
 OPENMPI)
     if [ -r $MPI_ARCH_PATH/lib${WM_COMPILER_LIB_ARCH}/libmpi.so ]
@@ -172,6 +198,8 @@ MPICH)
 
 esac
 
+fi # MPI MinGW or Linux
+
 
 # get SCOTCH_VERSION, SCOTCH_ARCH_PATH
 if settings=`$WM_PROJECT_DIR/bin/foamEtcFile config/scotch.sh`
@@ -182,6 +210,14 @@ else
     echo "Error: no config/scotch.sh settings"
     echo
 fi
+
+#either build the MinGW version or the standard version
+if isMinGW; then
+
+  ./AllwmakeMinGWScotch
+
+else
+
 
 # building scotch is still a bit of a pain
 echo ========================================
@@ -306,6 +342,7 @@ then
     }
 fi
 
+fi #end if isMinGW
 
 # -----------------------------------------------------------------------------
 
@@ -320,6 +357,50 @@ then
 fi
 if [ -d "$METIS_VERSION" ]
 then
+  if isMinGW; then
+  (
+
+    if [ -f $METIS_ARCH_PATH/include/metis.h \
+      -a -r $FOAM_EXT_LIBBIN/libmetis.dll ]
+    then
+        echo "    metis header in $METIS_ARCH_PATH/include"
+        echo "    metis libs   in $FOAM_EXT_LIBBIN"
+        echo
+    else
+        set -x
+        cd $METIS_VERSION  || exit 1
+        
+        if [ ! -e "mingw.patch.complete" ]; then
+            patch -p1 < $WM_THIRD_PARTY_DIR/etc/patches/patch_metis_5.1.0 && \
+              touch mingw.patch.complete
+        fi
+
+        [ -d build ] && rm -rf build
+        [ ! -d build ] && mkdir build
+
+        cd build
+        cmake \
+            -G "MSYS Makefiles" \
+            -DCMAKE_INSTALL_PREFIX=$METIS_ARCH_PATH \
+            -DCMAKE_BUILD_TYPE=Release \
+            -DSHARED=1 \
+            -DCMAKE_C_COMPILER=${WM_CC} \
+            -DGKLIB_PATH="../GKlib" \
+            -DCMAKE_C_FLAGS="$CFLAGS -DWIN${WM_ARCH_OPTION}" \
+            -DCMAKE_CXX_FLAGS="$CXXFLAGS -DWIN${WM_ARCH_OPTION}" \
+            $WM_THIRD_PARTY_DIR/$METIS_VERSION
+
+        make all install
+        cp $METIS_ARCH_PATH/lib/libmetis.dll* $FOAM_EXT_LIBBIN
+        cp $FOAM_EXT_LIBBIN/libmetis.dll.a $FOAM_EXT_LIBBIN/libmetis.a
+
+        #clean up afterwards
+        [ -d build ] && rm -rf build
+
+        set +x
+    fi
+  )
+  else
 
     if [ -f $METIS_ARCH_PATH/include/metis.h \
       -a -r $FOAM_EXT_LIBBIN/libmetis.so ]
@@ -336,6 +417,8 @@ then
         cp $METIS_ARCH_PATH/lib/libmetis.so $FOAM_EXT_LIBBIN
     )
     fi
+
+  fi
 else
     echo "    optional component Metis was not found"
 fi
@@ -344,7 +427,7 @@ fi
 # CGAL is optional
 echo ========================================
 echo Build CGAL
-if [ -n "$CGAL_ARCH_PATH" ]
+if [ -n "$CGAL_ARCH_PATH" ] && ! isMinGW
 then
 (
     if [ -r $CGAL_ARCH_PATH/lib/libCGAL.so ]
@@ -354,6 +437,30 @@ then
     else
         ./makeCGAL
     fi
+)
+else
+    echo "    optional component was not found"
+fi
+
+# -----------------------------------------------------------------------------
+
+# Tecio is optional
+echo ========================================
+echo Build Tecio
+if [ -d tecio ]
+then
+(
+    set -x
+    cd tecio || exit 1
+    cpMakeFiles tecio
+
+    if isMinGW && [ ! -e "mingw.patch.complete" ]; then
+        chmod -R +w *
+        patch -p1 < $WM_THIRD_PARTY_DIR/etc/patches/patch_tecio2009 && \
+          touch mingw.patch.complete
+    fi
+
+    wmake libso tecsrc
 )
 else
     echo "    optional component was not found"
