getMSYS2GccAsThirdParty: made the code more generic to support the versions defined in etc/config.sh/compiler

diff --git a/getMSYS2GccAsThirdParty b/getMSYS2GccAsThirdParty
--- a/getMSYS2GccAsThirdParty
+++ b/getMSYS2GccAsThirdParty
@@ -66,10 +66,18 @@ PACKAGE_SUFFIX="-any.pkg.tar.zst"
 # From makeGcc
 installBASE=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH
 GCC_ARCH_PATH=$installBASE/$gcc_version
+GCC_VERSION=${gcc_version/gcc-/}
 
 if [ ! -d "${GCC_ARCH_PATH}" ]
 then
     mkdir -p "${GCC_ARCH_PATH}"
+fi
+
+if [ -z "$MSYS2_GCC_PATCH" -o -z "$MSYS2_BINUTILS_VERSION" ]
+then
+    echo "Error: \$MSYS2_GCC_PATCH and/or \$MSYS2_BINUTILS_VERSION not set, "
+    echo "    therefore this is likely not properly configured."
+    exit 1
 fi
 
 #end of initializations -------------------------------------------
@@ -83,11 +91,11 @@ function downloadFromMSYS2Repo()
 
 #script start ------------------------------------------------------
 
-PACKAGES="binutils-2.39-3"
+PACKAGES="binutils-$MSYS2_BINUTILS_VERSION"
 
 for package in gcc gcc-libs gcc-fortran gcc-libgfortran
 do
-    PACKAGES="${PACKAGES} ${package}-12.2.0-11"
+    PACKAGES="${PACKAGES} ${package}-${GCC_VERSION}-${MSYS2_GCC_PATCH}"
 done
 
 for package in ${PACKAGES}
